export { default as Regions} from "./Regions"
export { default as Item } from "./Item"
export { default as Items } from "./Items"
export { default as Pokemon } from "./Pokemon"
export { default as Pokemons } from "./Pokemons"
export { default as Ability } from "./Ability"
export { default as Abilities } from "./Abilities"